apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "journals.fullname" . }}
  labels:
    {{- include "journals.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "journals.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "journals.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "journals.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
              - name: OJS_CLI_INSTALL
                value: "1"
            {{- if .Values.mariadb.enabled }}
              - name: OJS_DB_HOST
                value: {{ include "journals.fullname" . }}-mariadb
              - name: OJS_DB_USER
                value: {{ .Values.mariadb.user }}
              - name: OJS_DB_PASSWORD
                value: {{ .Values.mariadb.password }}
              - name: OJS_DB_NAME
                value: {{ .Values.mariadb.name }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
