{{- if .Values.mariadb.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "journals.fullname" . }}-mariadb
  labels:
    app.kubernetes.io/name: {{ include "journals.name" . }}-mariadb
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ include "journals.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "journals.name" . }}-mariadb
      app.kubernetes.io/instance: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: nfs-client
        resources:
          requests:
            storage: 8Gi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "journals.name" . }}-mariadb
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "journals.serviceAccountName" . }}
      volumes:
      containers:
        - name: {{ .Chart.Name }}-mariadb
          image: "{{ .Values.mariadb.image }}:{{ .Values.mariadb.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: data
          env:
            - name: MYSQL_USER
              value: {{ .Values.mariadb.user }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.name }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mariadb.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mariadb.rootPassword }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}