{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "journals.serviceAccountName" . }}
  labels:
{{ include "journals.labels" . | nindent 4 }}
{{- end -}}
