apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journals-
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://harbor.k8s.libraries.psu.edu/chartrepo/library
    targetRevision: 0.1.0
    chart: journals
    helm:
     values: |
        ingress:
          hosts:
          - host: journals--.dsrd.libraries.psu.edu
  destination:
    server: https://kubernetes.default.svc
    namespace: journals--
  syncPolicy:
    automated: {}
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
